### PR TITLE
Add OMSimulator's documentation

### PR DESCRIPTION
**Pull request by lochel**
Starting point for sphinx-based documentation.

### CODE REVIEW

**Comment by adeas31** [comment]
Why are you creating a separate documentation for OMSimulator?
Shouldn't it be part of OM documentation.

**Comment by lochel** [comment]
Actually, I am not sure about this. I think OMSimulator should be more or less independent from everything else. I agree, that it would be good to have it also in the OpenModelica documentation. However, I think there should also be a separate documentation. @bernhard-thiele what do you think?

**Comment by casella** [comment]
There absolutely needs to be some reference to OMSimulator in the [OpenModelica User Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/index.html). That is the entry point for documentation and should talk about the entire tool suite developed and maintained by the OSMC. Otherwise people (up to and including myself) will get confused.
I just googled ["OMSimulator site:openmodelica.org"](https://www.google.it/#q=%22OMSimulator%22+site:openmodelica.org) and the only references I find are a ticket and a mention of the tool in the release notes of the 1.12.0 alpha version. That's not good.
I think you should avoid duplications, so if there are good reasons to have a separate documentation of this tool, please make sure it is linked from the main User Guide table of contents.

**Comment by lochel** [comment]
Well, OMSimulator generates a lot of confusions. Right now, we have two tools developed under the umbrella of OMSimulator: OMFMISimulator and OMTLMSimulator. Until now, there is only a release of the OMTLMSimulator and that should be documented within the OpenModelica user’s guide ([see TLM](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/tlmcosimulation.html)). 

This repository is actually OMFMISimulator (I will probably rename the repository soon). There is no release yet and thus there is no need for a documentation in the OpenModelica user’s guide for now.

Moreover, the OMSimulator should be independent from other OpenModelica tools like omc/OMEdit. Therefore, a separate documentation is IMHO required. In addition, there should be also a chapter in the OpenModelica user’s guide, that, e.g., describes a potential integration into OMEdit and contains a cross reference to the standalone OMSimulator documentation.

I will include some more people that are involved to see what they think about this: @adrpo, @adeas31, @robbr48, @bernhard-thiele

**Comment by bernhard-thiele** [comment]
@lochel I agree that there should be an independent documentation since it should be possible to use the tool as a standalone tool. The OpenModelica user's guide should reference this documentation, or maybe, there is also a way to "embed" it.

**Comment by lochel** [comment]
I added the entire C-API and all lua scripting commands to the documentation. Now we have to add descriptions for all this and also examples and use cases as starting point for new users.

**Pull request merged**
